### ISSUE TITLE
electron issue: port 5000 ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Camillewz24340** [nobody48sheldor/CALC-5318008#2]
Distribution: Lubuntu 22.04

electron tries to load a connection on port 5000, but the connection is refused

![image](https://user-images.githubusercontent.com/75937480/209321715-be6ed4bf-48da-41dc-be01-7d0b7f96976f.png)

**Comment by nobody48sheldor** [comment]
Je sais pas si c'est un probleme au niveau d'electron, ou si c'est au niveau des threads du processeur. Dans tous les cas tu peux :

        -> essayes de changer le port, si jamais il y a en fait déjà quelque chose qui tourne sur le port 5000
        -> essayes de faire `killall electron` pour être sure qu'il n'y ait pas d'instances d'electron qui soit déjà sur le port 5000 et qui se seraient mal lancé

(in english, if people are having the same issue)
I don't know if it is more a thread issue or a electron issue. Either way, you can :

        -> try to change the port
        -> try to kill all electron instances, that may be running, with the command  `killall electron`
